apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crate.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crate.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.auth.username | default "crate" | quote }}
  POSTGRES_PASSWORD: {{ required "postgresql.auth.password is required" .Values.postgresql.auth.password | quote }}
  MINIO_ACCESS_KEY: {{ .Values.minio.auth.rootUser | default "crate" | quote }}
  MINIO_SECRET_KEY: {{ required "minio.auth.rootPassword is required" .Values.minio.auth.rootPassword | quote }}
  SECRET_KEY: {{ required "app.secretKey is required" .Values.app.secretKey | quote }}
