apiVersion: v2
name: crate
description: Crate Inventory Tracking Appliance
type: application
version: 0.2.9
appVersion: "0.2.9"
home: https://github.com/txdmc/crate
sources:
  - https://github.com/txdmc/crate
maintainers:
  - name: txdmc
keywords:
  - inventory
  - appliance
  - k3s
